spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      database: customer-db
      password: admin
      port: '27017'
      host: localhost

secret-key: 'DE2D6323AD62BD9F8A8BF55765DD7'