spring:
  config:
    import: optional:secret.yaml

server:
  port: 8082

queue:
  sms:
    name: 'sms-queue'
  car-request:
    name: 'car-request-queue'
  car-request-status:
    name: 'car-request-status-queue'