spring:
  config:
    import: secret.yaml

server:
  port: 8080

logging:
  file:
    name: 'wiber-back/src/main/resources/log/wiber-back.log'
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

queue:
  name: 'wiber-queue'