spring:
  config:
    import: secret.yaml

server:
  port: 8080

logging:
  file:
    name: '/home/kygor/IdeaProjects/taxi-booking-backend/wiber-back/src/main/resources/logs/wiber-back.log'
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG